name: Build and Push Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Static Site
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Avoids using the GITHUB_TOKEN to authenticate pushes

      - name: Set Up Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create or Checkout Build Branch
        run: |
          git fetch origin
          git checkout build || git checkout -b build

      - name: Copy Files to Build Directory
        run: |
          mkdir -p build
          cp -r * build/
        shell: bash

      - name: Commit and Push to Build Branch
        run: |
          cd build
          git init
          git remote add origin https://github.com/HarshitRajput0201/Landing-Page.git
          git add --all
          git commit -m "Deploy static site"
          git push --force origin build
