name: Build and Push Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Static Site
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create or Checkout Build Branch
        run: |
          git fetch origin
          git checkout build || git checkout -b build

      - name: Prepare Build Directory
        run: |
          mkdir -p deploy

      - name: Copy Files to Deploy Directory
        run: |
          rsync -av --exclude='deploy' . deploy/
        shell: bash

      - name: Commit and Push to Build Branch
        run: |
          cd deploy
          git init
          git remote add origin https://github.com/HarshitRajput0201/Landing-Page.git
          git add --all
          git commit -m "Deploy static site"
          git push --force origin build
