name: Build and Push Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Static Site
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push to Build Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build  # Branch where you want to push the built assets
          FOLDER: .  # Directory where your static assets are located
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
